#ddev-generated
services:
  ollama:
    container_name: ddev-${DDEV_SITENAME}-ollama
    image: ollama/ollama:latest
    restart: "no"
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
    - ".:/mnt/ddev_config"
    - "ddev-global-cache:/mnt/ddev-global-cache"
    - "ollama-model-data:/mnt/ollama-model-data/data"